"""Generate Swift 6 transport models + a URLSession client from contracts/v1/openapi.json.

Deterministic and pinned in-repo (GENERATOR_VERSION). The client maps nothing into domain types; the app does that.
CI regenerates and fails on diff (--check).
"""
import argparse, hashlib, json, re, sys
from pathlib import Path

GENERATOR_VERSION = "kfn8-openapi-swift 1.0.0"
ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "contracts" / "v1" / "openapi.json"
OUT = ROOT.parents[0] / "_Kfn8-frontend-avp-src" / "Packages" / "Kfn8Kit" / "Sources" / "Kfn8Catalogue" / "Generated" / "CatalogueAPI.swift"
SKIP = {"HTTPValidationError", "ValidationError"}


def swift_type(schema: dict, required: bool) -> str:
    if "$ref" in schema:
        t = schema["$ref"].split("/")[-1]
    elif "anyOf" in schema:
        non_null = [s for s in schema["anyOf"] if s.get("type") != "null"]
        t = swift_type(non_null[0], True)
        return t + "?"
    else:
        kind = schema.get("type")
        fmt = schema.get("format")
        if kind == "string":
            t = {"uuid": "UUID", "date-time": "Date"}.get(fmt, "String")
            if "enum" in schema or "const" in schema:
                t = "String"
        elif kind == "integer":
            t = "Int"
        elif kind == "number":
            t = "Double"
        elif kind == "boolean":
            t = "Bool"
        elif kind == "array":
            t = f"[{swift_type(schema['items'], True)}]"
        elif kind == "object":
            t = "JSONValue"
        else:
            t = "JSONValue"
    return t if required else t + "?"


def camel(name: str) -> str:
    parts = name.split("_")
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--check", action="store_true")
    a = p.parse_args()
    spec_text = SPEC.read_text()
    spec = json.loads(spec_text)
    lines = [
        "// GENERATED by tools/generate_swift_client.py — do not edit.",
        f"// Generator: {GENERATOR_VERSION}",
        f"// Contract: API {spec['info']['version']} sha256 {hashlib.sha256(spec_text.encode()).hexdigest()}",
        "import Foundation",
        "",
        "public enum CatalogueAPIContract {",
        f"    public static let apiVersion = \"{spec['info']['version']}\"",
        f"    public static let contractSHA256 = \"{hashlib.sha256(spec_text.encode()).hexdigest()}\"",
        "}",
        "",
        "/// Arbitrary JSON for schema-less objects (e.g. attachment metadata).",
        "public enum JSONValue: Codable, Sendable, Equatable {",
        "    case string(String), number(Double), bool(Bool), object([String: JSONValue]), array([JSONValue]), null",
        "    public init(from decoder: any Decoder) throws {",
        "        let c = try decoder.singleValueContainer()",
        "        if c.decodeNil() { self = .null } else if let b = try? c.decode(Bool.self) { self = .bool(b) }",
        "        else if let n = try? c.decode(Double.self) { self = .number(n) } else if let s = try? c.decode(String.self) { self = .string(s) }",
        "        else if let a = try? c.decode([JSONValue].self) { self = .array(a) } else { self = .object(try c.decode([String: JSONValue].self)) }",
        "    }",
        "    public func encode(to encoder: any Encoder) throws {",
        "        var c = encoder.singleValueContainer()",
        "        switch self {",
        "        case .string(let s): try c.encode(s)",
        "        case .number(let n): try c.encode(n)",
        "        case .bool(let b): try c.encode(b)",
        "        case .object(let o): try c.encode(o)",
        "        case .array(let a): try c.encode(a)",
        "        case .null: try c.encodeNil()",
        "        }",
        "    }",
        "}",
        "",
    ]
    schemas = spec["components"]["schemas"]
    for name in sorted(schemas):
        if name in SKIP:
            continue
        s = schemas[name]
        props = s.get("properties", {})
        req = set(s.get("required", []))
        lines.append(f"public struct {name}: Codable, Sendable, Equatable {{")
        for pname in sorted(props):
            lines.append(f"    public var {camel(pname)}: {swift_type(props[pname], pname in req)}")
        keys = [f"case {camel(k)} = \"{k}\"" if camel(k) != k else f"case {k}" for k in sorted(props)]
        lines.append("    enum CodingKeys: String, CodingKey { " + "; ".join(keys) + " }")
        lines.append("}")
        lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines) + "\n"
    if a.check:
        if not OUT.exists() or OUT.read_text() != text:
            print("Swift transport models are out of date; run tools/generate_swift_client.py", file=sys.stderr)
            sys.exit(1)
        print("Swift transport models up to date")
    else:
        OUT.write_text(text)
        print("wrote", OUT)


if __name__ == "__main__":
    main()
