"""initial catalogue schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 02:13:34.857314
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimension_spec',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('width_m', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('depth_m', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('height_m', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('authority_kind', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.Text(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_sha256', sa.String(length=64), nullable=False),
    sa.CheckConstraint("authority_kind IN ('retailer','operator')", name='ck_dimension_authority'),
    sa.CheckConstraint("evidence_sha256 ~ '^[0-9a-f]{64}$'", name='ck_dimension_evidence_hash'),
    sa.CheckConstraint('width_m > 0 AND depth_m > 0 AND height_m > 0', name='ck_dimension_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'tenant_id', name='uq_catalogue_id_tenant'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('asset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('catalogue_id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('affinity', sa.Text(), nullable=False),
    sa.Column('delivery_mode', sa.Text(), nullable=False),
    sa.Column('provenance', sa.Text(), nullable=False),
    sa.Column('style_tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('dominant_colour', sa.Text(), nullable=True),
    sa.Column('weight_class', sa.Text(), nullable=True),
    sa.Column('is_floor_covering', sa.Boolean(), nullable=False),
    sa.CheckConstraint("affinity IN ('floor','wall','ceiling','tabletop','freestanding-outdoor')", name='ck_asset_affinity'),
    sa.CheckConstraint("delivery_mode IN ('public','restricted')", name='ck_asset_delivery_mode'),
    sa.CheckConstraint("provenance IN ('licensed','commissioned','captured','generated')", name='ck_asset_provenance'),
    sa.ForeignKeyConstraint(['catalogue_id', 'tenant_id'], ['catalogue.id', 'catalogue.tenant_id'], name='fk_asset_catalogue_tenant', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sku', name='uq_asset_tenant_sku')
    )
    op.create_index('ix_asset_filters', 'asset', ['catalogue_id', 'category', 'affinity'], unique=False)
    op.create_index('ix_asset_name_id', 'asset', ['name', 'id'], unique=False)
    op.create_table('asset_revision',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('contract_version', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('dimension_spec_id', sa.UUID(), nullable=False),
    sa.Column('attachment_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(state = 'published') = (published_at IS NOT NULL) OR state IN ('revoking','revoked')", name='ck_revision_published_at'),
    sa.CheckConstraint("source_sha256 ~ '^[0-9a-f]{64}$'", name='ck_revision_source_sha'),
    sa.CheckConstraint("state IN ('draft', 'validating', 'review', 'approved', 'publishing', 'published', 'revoking', 'revoked', 'rejected')", name='ck_revision_state'),
    sa.CheckConstraint('revision > 0', name='ck_revision_positive'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dimension_spec_id'], ['dimension_spec.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'revision', name='uq_revision_asset_revision')
    )
    op.create_index('ix_revision_published', 'asset_revision', ['asset_id', 'state', 'revision'], unique=False)
    op.create_table('offer',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('retailer_url', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name='ck_offer_currency'),
    sa.CheckConstraint('amount_minor >= 0', name='ck_offer_amount'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('asset_id', 'market', 'currency')
    )
    op.create_index('ix_offer_asset', 'offer', ['asset_id'], unique=False)
    op.create_table('approval',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_reference', sa.Text(), nullable=False),
    sa.Column('evidence_sha256', sa.String(length=64), nullable=False),
    sa.Column('input_sha256', sa.String(length=64), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.CheckConstraint("evidence_sha256 ~ '^[0-9a-f]{64}$' AND input_sha256 ~ '^[0-9a-f]{64}$'", name='ck_approval_hashes'),
    sa.CheckConstraint("kind IN ('provenance','visual_dimensions')", name='ck_approval_kind'),
    sa.ForeignKeyConstraint(['revision_id'], ['asset_revision.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_approval_revision_kind', 'approval', ['revision_id', 'kind'], unique=False)
    op.create_table('ingestion_stage',
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('tool_version', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("state IN ('pending','running','passed','failed')", name='ck_stage_state'),
    sa.ForeignKeyConstraint(['revision_id'], ['asset_revision.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('revision_id', 'stage')
    )
    op.create_table('licence_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('licence_id', sa.Text(), nullable=False),
    sa.Column('attribution_required', sa.Boolean(), nullable=False),
    sa.Column('attribution_text', sa.Text(), nullable=True),
    sa.Column('evidence_reference', sa.Text(), nullable=False),
    sa.Column('evidence_sha256', sa.String(length=64), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("evidence_sha256 ~ '^[0-9a-f]{64}$'", name='ck_licence_evidence_hash'),
    sa.CheckConstraint('NOT attribution_required OR attribution_text IS NOT NULL', name='ck_licence_attribution_text'),
    sa.ForeignKeyConstraint(['revision_id'], ['asset_revision.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_id')
    )
    op.create_table('material_variant',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('material_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['asset_revision.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', 'revision_id')
    )
    op.create_table('rendition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('lod', sa.SmallInteger(), nullable=False),
    sa.Column('format', sa.Text(), nullable=False),
    sa.Column('variant_key', sa.Text(), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('triangles', sa.Integer(), nullable=False),
    sa.Column('max_texture_edge', sa.Integer(), nullable=False),
    sa.CheckConstraint("format IN ('glb','usdz')", name='ck_rendition_format'),
    sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name='ck_rendition_sha'),
    sa.CheckConstraint('lod BETWEEN 0 AND 2', name='ck_rendition_lod'),
    sa.CheckConstraint('max_texture_edge <= 2048', name='ck_rendition_texture'),
    sa.CheckConstraint('size_bytes > 0', name='ck_rendition_size'),
    sa.CheckConstraint('triangles >= 0', name='ck_rendition_triangles'),
    sa.ForeignKeyConstraint(['revision_id'], ['asset_revision.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key'),
    sa.UniqueConstraint('revision_id', 'lod', 'format', 'variant_key', name='uq_rendition_slot')
    )
    op.create_table('revocation',
    sa.Column('sequence', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removal_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purge_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("reason = 'rights'", name='ck_revocation_reason'),
    sa.ForeignKeyConstraint(['revision_id'], ['asset_revision.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('sequence'),
    sa.UniqueConstraint('revision_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revocation')
    op.drop_table('rendition')
    op.drop_table('material_variant')
    op.drop_table('licence_ledger')
    op.drop_table('ingestion_stage')
    op.drop_index('ix_approval_revision_kind', table_name='approval')
    op.drop_table('approval')
    op.drop_index('ix_offer_asset', table_name='offer')
    op.drop_table('offer')
    op.drop_index('ix_revision_published', table_name='asset_revision')
    op.drop_table('asset_revision')
    op.drop_index('ix_asset_name_id', table_name='asset')
    op.drop_index('ix_asset_filters', table_name='asset')
    op.drop_table('asset')
    op.drop_table('catalogue')
    op.drop_table('tenant')
    op.drop_table('dimension_spec')
    # ### end Alembic commands ###
